name: Check Lesson 05 Quiz Pull Request

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lesson_05/quiz/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build Shared Lib with Node.js
      working-directory: ./lib/typescript/codedifferently-instructional
      run: npm ci

    - name: Build Lesson 06 with Node.js
      working-directory: ./lesson_05/quiz
      run: |
        npm ci
        npm run check