name: Check Lesson 26 TS Pull Request

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lesson_26/api/javascript/api_app/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build Lesson 26 with Node.js
      working-directory: ./lesson_26/api/javascript/api_app
      run: |
        npm ci
        npm run check