name: Check Fullstack Demo Java Pull Request

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lib/java/fullstack_demo/**"

env:
  CLERK_PERISHABLE_KEY: 12345

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Fullstack Demo with Java
      working-directory: ./lib/java/fullstack_demo
      run: ./gradlew check